server:
  port: 8088

spring:
  logi-job:
    jdbc-url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    max-lifetime: 60000
    init-sql: true
    init-thread-num: 10
    max-thread-num: 20
    log-exipre: 3 # 日志保存天数，以天为单位
    app_name: logi_job_test
    claim-strategy: com.didiglobal.knowframework.job.core.consensual.RandomConsensual
    node-name: node1
    job-log-fetcher-extend-bean-name: com.didiglobal.knowframework.job.extend.impl.DefaultJobLogFetcherExtendImpl
    elasticsearch-address: 116.85.23.222
    elasticsearch-port: 18303
    elasticsearch-user: elastic
    elasticsearch-password: Didiyun@888
    elasticsearch-index-name: test
    elasticsearch-type-name: type
