name: elasticsearch-didi-internal-client
stages: 
    - name: compile
      trigger: manual
      jobs: 
        - name: compile-release-lib
          tasks: 
            - name: release-lib
              type: oe-release-lib
              params: 
                buildTool: MAVEN
                osType: centos7.2
                language: JAVA
