server:
  port: 8088


spring:
  auv-job:
    jdbc-url: jdbc:mysql://10.96.80.17:3306/auv_job?useUnicode=true&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: liuwu_test_001
    driver-class-name: com.mysql.jdbc.Driver
    max-lifetime: 60000
    init-sql: true
    init-thread-num: 10
    max-thread-num: 20
    log-expire: 3
