server:
  port: 8088

spring:
  logi-job:
    jdbc-url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    max-lifetime: 60000
    init-sql: true
    init-thread-num: 10
    max-thread-num: 20
    log-expire: 5 # 日志保存天数，以天为单位
    app_name: arius_test03
    claim-strategy: com.didiglobal.logi.job.core.consensual.RandomConsensual
