{
 "title": "metrics-job",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "applicationName",
    "label": "应用名",
    "query": "{\"find\":\"terms\",\"field\":\"applicationName\"}"
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": "{\"find\":\"terms\",\"field\":\"hostName\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "进程启动以来执行超时的任务数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "进程启动以来执行超时的任务数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"job.thread.pool.task.timeout.number\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "进程启动以来因执行调度任务的线程池队列满导致待执行的定时任务提交时被拒绝的定时任务数量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "进程启动以来因执行调度任务的线程池队列满导致待执行的定时任务提交时被拒绝的定时任务数量",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"job.rejected.task.number\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "执行定时任务的线程池的当前队列大小",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "执行定时任务的线程池的当前队列大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"job.thread.pool.queue.size\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "正在执行的任务数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "正在执行的任务数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"job.thread.pool.task.running.size\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "执行定时任务的线程池的最大线程数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "执行定时任务的线程池的最大线程数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"job.thread.pool.thread.size.max\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  }
 ]
}