{
 "title": "metrics-sql-task-api",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "applicationName",
    "label": "应用名",
    "query": "{\"find\":\"terms\",\"field\":\"applicationName\"}"
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": "{\"find\":\"terms\",\"field\":\"hostName\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "api调用失败次数top5/分钟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "httpTarget",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "spanKind : \"SERVER\" AND statusData : \"ERROR\" AND applicationName : $applicationName AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "调度任务运行失败次数top5/分钟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "JobClassName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "spanKind : \"CRON_TASK\" AND statusData : \"ERROR\" AND applicationName : $applicationName AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "api调用运行平均耗时top5/分钟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "httpTarget",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "spentNanos",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "spanKind : \"SERVER\" AND applicationName : $applicationName AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "api调用次数top5/分钟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "httpTarget",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "spanKind :\"SERVER\" AND applicationName : $applicationName AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "api调用运行最大耗时top5/分钟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "httpTarget",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "spentNanos",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "spanKind : \"SERVER\" AND applicationName : $applicationName AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "调度任务运行平均耗时top5/分钟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "JobClassName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "spentNanos",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "spanKind : \"CRON_TASK\" AND applicationName : $applicationName AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "调度任务运行最大耗时top5/分钟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "JobClassName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "spentNanos",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "spanKind : \"CRON_TASK\" AND applicationName : $applicationName AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "调度任务运行次数top5/分钟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "JobClassName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "spanKind : \"CRON_TASK\" AND applicationName : $applicationName AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "sql运行平均耗时top5/分钟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sqlStatement",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "logMills",
       "id": "3",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "spentNanos",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(sqlType : \"SELECT\" OR sqlType : \"UPDATE\" OR sqlType : \"INSERT\" OR sqlType : \"DELETE\") AND applicationName : $applicationName AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "sql运行最大耗时/分钟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sqlStatement",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "logMills",
       "id": "4",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "spentNanos",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "(sqlType : \"SELECT\" OR sqlType : \"UPDATE\" OR sqlType : \"INSERT\" OR sqlType : \"DELETE\") AND applicationName : $applicationName AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "sql运行次数top5/分钟",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "sqlStatement",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "(sqlType : \"SELECT\" OR sqlType : \"UPDATE\" OR sqlType : \"INSERT\" OR sqlType : \"DELETE\") AND applicationName : $applicationName AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  }
 ]
}