{
 "title": "metrics-system",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "主机名",
    "query": "{\"find\":\"terms\",\"field\":\"hostName\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "源时钟与本地时钟的时间差（单位：秒）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "源时钟与本地时钟的时间差",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.ntp.offset.gap\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "系统CPU核数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "系统CPU核数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.cpu.cores\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "系统CPU使用率(单位：%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "系统CPU使用率",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.cpu.util\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "虚拟CPU等待实际CPU时间的百分比（单位：%）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "虚拟CPU等待实际CPU时间的百分比",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.cpu.steal\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "系统近1分钟平均负载",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "系统近1分钟平均负载",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.cpu.load.1\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "系统内存信息概览",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "系统内存总大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.memory.total\" AND hostName : $hostname",
     "timeField": "logMills"
    },
    {
     "alias": "系统空闲内存大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.memory.free\" AND hostName : $hostname",
     "timeField": "logMills"
    },
    {
     "alias": "块设备占用的缓存页",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.memory.buffered\" AND hostName : $hostname",
     "timeField": "logMills"
    },
    {
     "alias": "普通文件所占用的缓存页",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.memory.cached\" AND hostName : $hostname",
     "timeField": "logMills"
    },
    {
     "alias": "系统已用swap大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.memory.swap.used\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "设备I/O请求的时间百分比（单位：%）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "deviceName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.io.util\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "设备平均IO队列长度",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "deviceName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.io.avgqusz\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "磁盘各分区总量大小",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "diskPath",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.disk.total\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "磁盘各分区余量大小",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "diskPath",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.disk.free\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "系统可以打开的最大文件句柄数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "系统可以打开的最大文件句柄数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.fd.files.max\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "系统使用文件句柄占已分配百分比（单位：%）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "系统使用文件句柄占已分配百分比",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.fd.files.used.percent\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "各网卡设备每秒下行流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "deviceName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.net.card.receive.bytes.per.second\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "各网卡设备每秒上行流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "deviceName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.net.card.send.bytes.per.second\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "系统网络每秒上、下行流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "系统网络每秒上行流量",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.net.work.send.bytes.per.second\" AND hostName : $hostname",
     "timeField": "logMills"
    },
    {
     "alias": "系统网络每秒下行流量",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.net.work.receive.bytes.per.second\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "系统tcp连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "系统tcp连接数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"system.net.work.tcp.connection.num\" AND hostName : $hostname",
     "timeField": "logMills"
    }
   ]
  }
 ]
}