{
 "title": "metrics-process",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "主机名",
    "query": "{\"find\":\"terms\",\"field\":\"hostName\"}"
   },
   {
    "name": "applicationName",
    "label": "应用名",
    "query": "{\"find\":\"terms\",\"field\":\"applicationName\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "进程运行时间",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.run.time\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "进程CPU使用概览",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "进程CPU使用率",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.cpu.util\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程内核态CPU使用率",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.cpu.system\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程用户态CPU使用率",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.cpu.user\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "进程CPU每秒上下文交换次数概览",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "进程CPU每秒上下文交换次数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.cpu.switches.per.second\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "当前进程CPU每秒自愿上下文交换次数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.cpu.voluntary.switches.per.second\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "当前进程CPU每秒非自愿上下文交换次数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.cpu.non.voluntary.switches.per.second\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "当前进程内存使用量概览",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "当前进程内存使用量",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.memory.used\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程堆内存使用量",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.heap.memory.used\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程堆外内存使用量",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.non.heap.memory.used\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程最大可用堆内存",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.heap.size.xmx\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程启动以来内存使用量峰值",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.memory.used.peak\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "当前进程内存使用率概览（单位：%）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "当前进程内存使用率",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.memory.util\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM堆内存使用率",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.heap.memory.used.percent\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "当前进程IO读、写速率/S",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "当前进程IO读取速率",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.io.read.bytes.per.second\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "当前进程IO写入速率",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.io.write.bytes.per.second\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "JVM GC 次数概览",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "JVM Young GC 次数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.young.gc.count.last.1.minute\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM Full GC 次数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.full.gc.count.last.1.minute\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "JVM GC 耗时概览",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "JVM Young GC 耗时",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.young.gc.time.last.1.minute\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM Full GC 耗时",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.full.gc.time.last.1.minute\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "JVM进程各区域大小 & 使用量大小概览",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "JVM进程第一个幸存区大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.s0c\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程第二个幸存区大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.s1c\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程第一个幸存区使用量大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.s0u\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程第二个幸存区使用量大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.s1u\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程 Eden 区大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.ec\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程 Eden 区使用量大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.eu\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程老年代大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.oc\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程老年代使用量大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.ou\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程方法区大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.mc\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程方法区使用量大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.mu\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程压缩类空间大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.ccsc\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程压缩类空间使用量大小",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.ccsu\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "JVM 线程数概览",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "JVM进程内的线程总数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.thread.num\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "JVM进程启动以来线程数峰值",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.jvm.thread.num.peak\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "进程已打开的 FD 数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "进程已打开的 FD 数量",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.open.fd.count\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "进程每秒上、下行流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "进程每秒下行流量",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.receive.bytes.per.second\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程每秒上行流量",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.send.bytes.per.second\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  },
  {
   "title": "TCP 连接数概览",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "进程 TCP 连接数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.tcp.connection.num\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程处于 LISTENING 状态的 TCP 连接数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.tcp.listening.num\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程处于 TIME_WAIT 状态的 TCP 连接数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.tcp.time.wait.num\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程处于 CLOSE_WAIT 状态的 TCP 连接数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.tcp.close.wait.num\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程处于 ESTABLISHED 状态的 TCP 连接数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.tcp.established.num\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程处于 SYN_SENT 状态的 TCP 连接数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.tcp.syn.sent.num\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程处于 SYN_RECV 状态的 TCP 连接数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.tcp.syn.recv.num\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程处于 FIN_WAIT_1 状态的 TCP 连接数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.tcp.fin.wait.1.num\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程处于 FIN_WAIT_2 状态的 TCP 连接数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.tcp.fin.wait.2.num\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程处于 CLOSED 状态的 TCP 连接数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.tcp.closed.num\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程处于 CLOSING 状态的 TCP 连接数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.tcp.closing.num\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    },
    {
     "alias": "进程处于 LAST_ACK 状态的 TCP 连接数",
     "bucketAggs": [
      { "field": "logMills", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "metricValue",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "logType : \"METRIC\" AND metricName: \"process.net.work.tcp.last.ack.num\" AND hostName : $hostname AND applicationName : $applicationName",
     "timeField": "logMills"
    }
   ]
  }
 ]
}